### ISSUE TITLE
Uncaught SyntaxError

### ISSUE THREAD

**Issue by dav04** [bendavis78/paper-time-picker#10]
I'm trying to use both paper-date-picker and paper-time-picker; when I import paper-date-picker, it works great but when I import paper-time-picker I have an endless loop of Uncaught SyntaxError: unexpected token <.
What I can do?

**Comment by bendavis78** [comment]
Can you give some code to reproduce the issue?

**Comment by dav04** [comment]
I can give you what I import but I don't know if it's the cause of the issue:
webcomponents-lite.min.js
jquery-2.1.3.js

and then I import all this polymer component:
Iron elements:
iron-icons.html
social-icons.html
image-icons.html
iron-icon.html
iron-collapse.html
iron-pages.html
iron-overlay-behavior.html
iron-form.html
iron-ajax.html
iron-input.html

Paper elements:
paper-icon-button.html
paper-drawer-panel.html
paper-header-panel.html
paper-toolbar.html
paper-menu.html
paper-submenu.html
paper-menu-button.html
paper-item.html
paper-button.html
paper-input.html
paper-input-container.html
paper-textarea.html
paper-material.html
paper-dialog.html
paper-toast.html
paper-styles.html
paper-checkbox.html
paper-badge.html
paper-card.html
paper-tooltip.html
paper-icon-item.html
paper-item-body.html
paper-radio-group.html
paper-radio-button.html
paper-dropdown-menu.html
paper-tabs.html

Neon animations:
neon-animation.html

App Router:
app-router.html
pushstate-anchor.html

maybe something is in conflict...

**Comment by bendavis78** [comment]
I'm not able to reproduce this. If you're still experiencing a problem, please provide an reproducible example on something like jsbin.
