### ISSUE TITLE
Problem setting hour

### ISSUE THREAD

**Issue by beppino** [bendavis78/paper-time-picker#12]
Hello,
I've found out a problem when the user try to set an hour from 0:00 am to 0:59 am.
The element goes to loop between hourChanged and periodChanger methods; the browser stop execution with an error.
Thanks a lot for yours components!
Bye
-g

**Comment by MrAntix** [comment]
I have the same problem bind to time
I've branched the code and refactored and its ok now (for binding to time anyway)

problem is, there is no tests in this project, so I don't feel confident I haven't broken other functionality, so I can't make a pull request  :(

**Comment by beppino** [comment]
Thanks @MrAntix, good job.
I'll use your fork but maybe its better to wait for @bendavis78 for a safe solution.
Bye

**Comment by MrAntix** [comment]
@beppino sure,  either way :)

**Comment by bendavis78** [comment]
Hi all, the recursion issue should be fixed in master. Let me know if you're still having issues. Sorry for the lack of tests! I'll add an issue for that. PR's welcome!

**Comment by beppino** [comment]
Thanks a lot.
But maybe you missed to update version number. Bower update doesn't find new version...
It's my fault?
Thanks again
