### ISSUE TITLE
Polymer 1.2.0 issues

### ISSUE THREAD

**Issue by opus1269** [bendavis78/paper-time-picker#16]
Polymer 1.2.0 was released yesterday and seems to have broken this element. All the clock face numbers are piled on top of each other in the top left corner.
https://github.com/Polymer/polymer/releases

![time](https://cloud.githubusercontent.com/assets/10528250/10707688/126b1b36-79bc-11e5-9186-8289b0dbd15a.jpg)

**Comment by opus1269** [comment]
Created a pull request that fixes this. Not exactly sure if this is a bug or a feature in Polymer 1.2.0

https://github.com/bendavis78/paper-time-picker/pull/17

**Comment by bendavis78** [comment]
Hey, sorry, I noticed the issue my self before seeing your PR. Fixed it in d8ec0fb.
