### ISSUE TITLE
TypeError: dom.g.classList[["remove", "add"][+ (obj.selected)]] is not a function

### ISSUE THREAD

**Issue by dhineshdhanapal** [bendavis78/paper-time-picker#19]
Good day,

I used paper-date-picker. It works fine. When I include paper-time-picker it gives me the error mentioned in the title. I don't know what is the real problem. Can you help me to fix this?.

TypeError: dom.g.classList[["remove", "add"][+ (obj.selected)]] is not a function

dom.g.classList[['remove', 'add'][+obj.selected]]('selected'); break;

this error mentioned in "paper-clock-selector.html" line number 248.

**Comment by bendavis78** [comment]
Can you provide some code that will reproduce the error?

**Comment by bendavis78** [comment]
Closing, as this line of code is no longer in master.
