### ISSUE TITLE
Failed to execute 'matches' on 'Element': ''[name' is not a valid selector.

### ISSUE THREAD

**Issue by naturalethic** [bendavis78/paper-time-picker#24]
Getting this error when using paper-time-picker as a child of a custom defined component that uses webcomponents, but not polymer.

```
Uncaught SyntaxError: Failed to execute 'matches' on 'Element': ''[name' is not a valid selector.
DomApi.queryDistributedElements @ polymer-mini.html:702
Polymer.IronSelectableBehavior._updateItems @ iron-selectable.html:221
Polymer.IronSelectableBehavior.attached @ iron-selectable.html:147
Polymer.Base._addFeature._invokeBehavior @ polymer-micro.html:392
Polymer.Base._addFeature._doBehavior @ polymer-micro.html:385(anonymous function) @ polymer-micro.html:196
Polymer.RenderStatus.whenReady @ polymer-micro.html:110
Polymer.Base.attachedCallback @ polymer-micro.html:194
Polymer.Base._addFeature.attachedCallback @ polymer-mini.html:100
```

**Comment by naturalethic** [comment]
I'll add the the value of the selector is correct (`[name]`) for a few calls on init, but two of them fail with the strange mangled version.

**Comment by bendavis78** [comment]
Can you see if you can reproduce this using plunker, jsbin, jsfiddle, etc? You can use the following plunker as a starting point: http://plnkr.co/edit/gVQluG0GrFP3RzCPZPIi

**Comment by naturalethic** [comment]
Hey Ben, we have dropped paper/polymer stuff for the time being.  But I believe the problem for this one might have been that we are using virtual-dom, and html-to-vdom, the latter of which removes attributes it knows to be builtins for standard elements.

**Comment by admwx7** [comment]
In that case @naturalethic I'm going to go ahead and close this issue out, seams like it's really an interop problem that we won't have much control over until v1 compliance across all browsers (which will be very soon!)
