### ISSUE TITLE
Clock is off on firefox.

### ISSUE THREAD

**Issue by srikkbhat** [bendavis78/paper-time-picker#25]
Looks like the <a href=https://github.com/bendavis78/paper-time-picker/blob/1.1.1/paper-clock-selector.html#L372">width and height</a> are not setting in firefox. 

I tried using <a href=https://www.polymer-project.org/1.0/docs/devguide/styling.html#style-api>customStyle variable followed by updateStyles</a> and it works.

Update: appending `'px'` to width and height works too.

**Comment by bendavis78** [comment]
merged. thanks!
