### ISSUE TITLE
arms of a clock not moving or moving extremely slow

### ISSUE THREAD

**Issue by vitalygoji** [bendavis78/paper-time-picker#30]
I added paper-time-picker to my application. Everything is working fine, I don't get error messages, but arms of a clock are not responding to mouse. Sometimes if I press mouse few times clock arm will "jump" to a different position..
May be someone experienced this issue. 
I use latest (week old) Polymer version.
Thank you for excellent components!

**Comment by kpprogrammer** [comment]
In IE and Edge browsers, the clock arm doesn't move at all.  If a time is already set and the dialog is opened, the time is not reflected by the arm either.  The arm is always at the 12 position for hour and 00 position for minutes.  When I try to click and drag the arm, it doesn't move.  I can click on a different hour or minute and it will reflect that in the time display portion, but the arm doesn't move to where I clicked.  We need to support these browsers.  I attached screen shots to show where the arm always displays and stays. Will this get fixed any time soon?
![hour_arm](https://cloud.githubusercontent.com/assets/17415264/14249794/1ab20f10-fa41-11e5-91b3-3e26415b1745.PNG)
![minutes_arm](https://cloud.githubusercontent.com/assets/17415264/14249795/1ab67a46-fa41-11e5-8654-f142bcc7cdf4.PNG)

**Comment by frezelth** [comment]
Hi,
Same issue here for IE11, the cloak arms don't move.
Is a fix available?

**Comment by admwx7** [comment]
A fix was merged in for this, are you still experiencing issues @frezelth?

**Comment by admwx7** [comment]
I just re-tested in IE11 and Edge and don't have this issue, going to go ahead and close this out.
