### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by salanford** [bendavis78/paper-time-picker#31]
paper-time-picker does not work in IE11 at all and shows the error "Unable to get property 'add' of undefined or null reference". To reproduce just run your basic Plunker test page (http://plnkr.co/edit/gVQluG0GrFP3RzCPZPIi) in IE11.

**Comment by kpprogrammer** [comment]
I am running into this issue as well.  SVG classList is not supported in IE, only className.  Because of this error, my page won't even render.  If fails in paper-clock-selector here:
function create(type, classList) {
            var el = document.createElementNS(SVG_NS, type);
            if (classList) {
              classList.forEach(function(c) {
                el.classList.add(c);
              });
            }
            if (!Polymer.Settings.useNativeShadow) {
              el.classList.add('style-scope');
              el.classList.add('paper-clock-selector');
            }
            return el;
          }
 and here: this.$.clock.classList.remove('animating');...

**Comment by urbanjaklin** [comment]
It seems that this error is still persistent in IE11! I'm not able to load the paper-time-picker and get the following errors:
![ie11paper-time-picker](https://cloud.githubusercontent.com/assets/21183080/21596018/fbefd10e-d102-11e6-83c0-f8be7f55ff35.PNG)

**Comment by mgibas** [comment]
Same here -do we have workaround for this ?
From a quick research [this line](https://github.com/bendavis78/paper-time-picker/blob/master/paper-clock-selector.html#L317) throws:

```js
if (classList) {
  classList.forEach(function(c) {
    el.classList.add(c); //el.classList is undefined
  });
}
```

**Comment by mgibas** [comment]
So, it seems that IE11 does not support `classList` for SVG :(
Had to add this polyfill:
https://github.com/beck/classlist-polyfill

its a fork with special fix for IE11.
