### ISSUE TITLE
Element does not resize for small screen

### ISSUE THREAD

**Issue by Yannike** [bendavis78/paper-time-picker#32]
When testing the element on a phone screen, the narrow configuration is not narrow enough, it gets cut on the side of the sceen. The radius of the clocked doesn't appear to change except when changing the layout type. It is always 148 when vertical.

**Comment by bendavis78** [comment]
What were the dimensions of the screen you tested on?

**Comment by Yannike** [comment]
I think I tried on a Nexus 4 screen using the chrome developer tool. (384x640)

**Comment by admwx7** [comment]
@Yannike are you still experiencing this issue?

**Comment by admwx7** [comment]
I was able to test it against 360x640 (nexus 5) and 384x640 without having this issue
