### ISSUE TITLE
Time Picker wrongly switches PM to AM 

### ISSUE THREAD

**Issue by vitalygoji** [bendavis78/paper-time-picker#33]
To replicate:
1)Open this component <paper-time-picker ' time='4:30 PM'>
2)You should see 4:30 PM. Click on "30" or anywhere,  VALUE switches to AM  display still shows PM in bold.

**Comment by bendavis78** [comment]
I can't replicate this. What browser?

**Comment by vitalygoji** [comment]
Chrome

**Comment by vitalygoji** [comment]
Chrome on Ubuntu

**Comment by admwx7** [comment]
@vitalygoji are you still experiencing this issue?
