### ISSUE TITLE
Can't change hours

### ISSUE THREAD

**Issue by mrbinr** [bendavis78/paper-time-picker#36]
Hi 
I'm trying to use paper-time-picker but i can't change hours ... nothing append, and when i click on minutes, number color change into white and i can't see then anymore :(

Best Regards
Pascall

**Comment by olegabr** [comment]
+1
ubuntu, firefox, chrome

**Comment by bendavis78** [comment]
Can't reproduce this on my end. Please see README under "Reporting Bugs".

**Comment by admwx7** [comment]
@mrbinr and @olegabr if either of you are still having this issue, please let me know, otherwise I'm going to close this out since I'm not having this issue either.
