### ISSUE TITLE
Broken with Firefox

### ISSUE THREAD

**Issue by balat** [bendavis78/paper-time-picker#4]
Hi,
The demo seems to be broken with Firefox. Tested with Iceweasel 38.0.1 on Debian.
The clock is not centered in the window and it is almost impossible to pick a value.
Can you reproduce this?
Thanks!
Vincent

**Comment by bendavis78** [comment]
I've fixed the issue in the 0.1 branch, however for 1.0 a new issue has popped up with regard to svg templates. I've opened a new issue for that.
