### ISSUE TITLE
Styling for `enableSeconds` is broken

### ISSUE THREAD

**Issue by sp1rs** [bendavis78/paper-time-picker#43]
Can we add seconds in picker ?

**Comment by bendavis78** [comment]
This would fall out of scope of what's shown in the material design spec, as well as most time picker components.

**Comment by bendavis78** [comment]
This is done using `enableSeconds`. Though it seems the styling for this is broken. I'm renaming this issue to reflect that.

**Comment by sp1rs** [comment]
`enableSeconds` works fine. Didn't see  any styling issue.

**Comment by admwx7** [comment]
I wasn't able to reproduce the styling issue (and it's stale), going to close this.  If someone notices the issue again please screenshot it in a new issue and tag me!
