### ISSUE TITLE
Second open() skips hours

### ISSUE THREAD

**Issue by rwestlund** [bendavis78/paper-time-picker#45]
### Versions
- paper-time-picker 1.1.2
- polymer 1.6.1
### Steps to reproduce
1. Open the time picker, select an hour and minute, and confirm.
2. Open the time picker again, without recreating the element.
### Expected behavior

Regardless of how many times the picker is opened, hours should be shown first.
### Actual behavior

When I open the time picker a second time, it shows the minute picker, bypassing the hour picker.
### Cause

It looks like `this.mode` is set to `hours` in `ready()`, but nothing else resets it back to hours.  It could be reset during `open()`, or perhaps a `reset()` function could be added.

Thanks for such a great element :)

**Comment by bendavis78** [comment]
Open/close isn't really a feature of the time picker -- that's the job of the dialog. You can set the `view` property to `"hours"` when the dialog closes to reset it. I've updated the demo to show how this is done.

**Comment by rwestlund** [comment]
That works, thanks.
