### ISSUE TITLE
Polymer 2.0 Support

### ISSUE THREAD

**Issue by rwestlund** [bendavis78/paper-time-picker#53]
Any plans to make this a hybrid element compatible with Polymer 2.0?

**Comment by ThilinaTCH** [comment]
@bendavis78 Is this in road map? If so any estimated date please..

**Comment by Saneyan** [comment]
Sent [a pull request](https://github.com/bendavis78/paper-time-picker/pull/54) to support Polymer 2.0.

**Comment by ArthurJahn** [comment]
In fact, there are still changes to be mande in [paper-time-picker](https://github.com/bendavis78/paper-time-picker/blob/master/paper-time-picker.html#L210) and [paper-clock-selector](https://github.com/bendavis78/paper-time-picker/blob/master/paper-clock-selector.html#L457). I'm having errors with `property-accessors` related to query-selector and/or dom-if
<img width="496" alt="captura de tela 2017-06-09 as 13 43 44" src="https://user-images.githubusercontent.com/2107018/26985414-ccf82908-4d19-11e7-9f0f-736841a8c1ab.png">
Did you get any problem like this? In general the component works well, but you have to tap the hour/minute before selecting its value, might be related to this query-selector error.

**Comment by amanshu-kataria** [comment]
@bendavis78 Can we expect it to support Polymer 2 any soon?

**Comment by admwx7** [comment]
@amanshu-kataria I'll be putting out a PR to support hybrid when I get some free time, sorry for being so inactive on here, promised I'd do some stuff to help out a while back and got slammed with work!

**Comment by amanshu-kataria** [comment]
@admwx7 thanks. BTW I tried migrating the code to Polymer 2, but facing some issues.
If you have some time then please check it. Here's the [link](https://github.com/amanshu-kataria/paper-time-picker/tree/2.0-bugs) to branch. And here's the [issue](https://github.com/amanshu-kataria/paper-time-picker/issues/1).

**Comment by admwx7** [comment]
I saw that. I've been migrating a lot of elements to hybrid at work and creating a few new ones as well so I've got the pattern down pretty solid, just need some free time to write some tests before I start the conversion to ensure I don't break anything

**Comment by amanshu-kataria** [comment]
@admwx7 please let me know what all I can do to help you. I would love to. :)

**Comment by admwx7** [comment]
I'm hoping to push the testing scaffold with a few basic tests and version
bump this weekend, after that if you want to add some additional tests,
that would be great!

**Comment by admwx7** [comment]
^1.2.0 should pick up the release candidate tag I just added against these changes, anyone feel daring enough to give it a try?  We'll be integrating things on our side in the near future and releasing an official 1.2.0 once we've gone through that but additional testing in other apps would be nice.

**Comment by rwestlund** [comment]
I've been using 1.2.0-rc2 in production for several months now with no problems.  Let's make it official and move on to Polymer 3 support.

**Comment by admwx7** [comment]
No one has complained, closing this out.
