### ISSUE TITLE
Cannot data-bind time

### ISSUE THREAD

**Issue by SylarRuby** [bendavis78/paper-time-picker#6]
`<paper-time-picker id="timePicker" hour="{{hour}}" minute="{{minute}}"></paper-time-picker>`

Below generates "Uncaught Invalid number paper-time-picker.html:201"

`<input is="iron-input" id="repair-time" bind-value="{{hour}}">`

any fix?

**Comment by bendavis78** [comment]
You're likely getting that error because of invalid input. You'll need to either add input validation (eg, with paper-input) or bind an intermediary variable and set the time variable manually.
